services:
  todo-app:
    container_name: todo-app
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL:postgres://postgres:postgres@localhost:5432/todos}
    depends_on:
      - postgres
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    env_file:
      - .env
  postgres:
    image: postgres:16.10-alpine3.21
    environment:
      POSTGRES_USER: ${POSTGRES_USER:postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:postgres_pwd}
      POSTGRES_DB: ${POSTGRES_DB:todos}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
